package Alexa;

import java.io.*;
import java.util.*;


public class CountryCodeConverter {
	private HashMap<String, String> converter = new HashMap<String, String>();

	public CountryCodeConverter() {
		converter.put("O","Others");
		converter.put("AF","Afghanistan");
		converter.put("AL","Albania");
		converter.put("DZ","Algeria");
		converter.put("AR","Argentina");
		converter.put("AM","Armenia");
		converter.put("AU","Australia");
		converter.put("AT","Austria");
		converter.put("AZ","Azerbaijan");
		converter.put("BS","Bahamas");
		converter.put("BH","Bahrain");
		converter.put("BD","Bengladesh");
		converter.put("BB","Barbados");
		converter.put("BY","Belarus");
		converter.put("BE","Belgium");
		converter.put("BM","Bermuda");
		converter.put("BO","Bolivia");
		converter.put("BA","Bosnia and Herzegovina");
		converter.put("BR","Brazil");
		converter.put("BN","Brunei");
		converter.put("BG","Bulgaria");
		converter.put("KH","Cambodia");
		converter.put("CA","Canada");
		converter.put("CL","Chile");
		converter.put("CN","China");
		converter.put("CO","Colombia");
		converter.put("CR","Costa Rica");
		converter.put("CI","Cote d'Ivoire");
		converter.put("HR","Croatia");
		converter.put("CW","Curacao");
		converter.put("CY","Cyprus");
		converter.put("CZ","Czech Rebublic");
		converter.put("DK","Denmark");
		converter.put("DO","Dominican Rebublic");
		converter.put("EC","Ecuador");
		converter.put("EG","Egypt");
		converter.put("LT","Lithuania");
		converter.put("MO","Macao");
		converter.put("MK","Macedonia");
		converter.put("MG","Madagascar");
		converter.put("MY","Malaysia");
		converter.put("MV","Maldives");
		converter.put("MT","Malta");
		converter.put("MQ","Martinique");
		converter.put("MU","Mauritius");
		converter.put("MX","Mexico");
		converter.put("MD","Moldova");
		converter.put("MN","Mongolia");
		converter.put("ME","Montenegro");
		converter.put("MA","Morocco");
		converter.put("MM","Myanmar");
		converter.put("NP","Nepal");
		converter.put("NL","Netherlands");
		converter.put("NC","New Caledonia");
		converter.put("NZ","New Zealand");
		converter.put("NI","Nicaragua");
		converter.put("NG","Nigeria");
		converter.put("NO","Norway");
		converter.put("OM","Oman");
		converter.put("PK","Pakistan");
		converter.put("PS","Palestinian Territory");
		converter.put("PA","Panama");
		converter.put("PY","Paraguay");
		converter.put("PE","Peru");
		converter.put("PH","Philippines");
		converter.put("PL","Poland");
		converter.put("PT","Portugal");
		converter.put("PR","Puerto Rico");
		converter.put("QA","Qatar");
		converter.put("RE","Reunion");
		converter.put("SV","El Salvador");
		converter.put("EE","Estonia");
		converter.put("FI","Finland");
		converter.put("FR","France");
		converter.put("PF","French Polynesia");
		converter.put("GE","Georgia");
		converter.put("DE","Germany");
		converter.put("GH","Ghana");
		converter.put("GI","Gibraltar");
		converter.put("GR","Greece");
		converter.put("GP","Guadeloupe");
		converter.put("GU","Guam");
		converter.put("GT","Guatemala");
		converter.put("HN","Honduras");
		converter.put("HK","Hong Kong");
		converter.put("HU","Hungary");
		converter.put("IS","Iceland");
		converter.put("IN","India");
		converter.put("ID","Indonesia");
		converter.put("IR","Iran");
		converter.put("IQ","Irak");
		converter.put("IE","Ireland");
		converter.put("IM","Isle of Man");
		converter.put("IL","Israel");
		converter.put("IT","Italy");
		converter.put("JM","Jamaica");
		converter.put("JP","Japan");
		converter.put("JO","Jordan");
		converter.put("KZ","Kazakhstan");
		converter.put("KE","Kenya");
		converter.put("KW","Kuwait");
		converter.put("KG","Kyrgystan");
		converter.put("LV","Latvia");
		converter.put("LB","Lebanon");
		converter.put("LY","Libya");
		converter.put("RO","Romania");
		converter.put("RU","Russia");
		converter.put("LC","Saint Lucia");
		converter.put("SA","Saudi Arabia");
		converter.put("RS","Serbia");
		converter.put("SG","Singapore");
		converter.put("SK","Slovakia");
		converter.put("SI","Slovenia");
		converter.put("ZA","South Africa");
		converter.put("KR","South Korea");
		converter.put("ES","Spain");
		converter.put("LK","Sri Lanka");
		converter.put("SD","Sudan");
		converter.put("SE","Sweden");
		converter.put("CH","Switzerland");
		converter.put("SY","Syria");
		converter.put("TW","Taiwan");
		converter.put("TZ","Tanzania");
		converter.put("TH","Thailand");
		converter.put("TT","Trinidad and Tobago");
		converter.put("TN","Tunisia");
		converter.put("TR","Turkey");
		converter.put("VI","US Virgin Islands");
		converter.put("UG","Uganda");
		converter.put("UA","Ukraine");
		converter.put("AE","United Arab Emirates");
		converter.put("GB","United Kingdom");
		converter.put("US","United States");
		converter.put("UY","Uruguay");
		converter.put("UZ","Uzbekistan");
		converter.put("VE","Venezuela");
		converter.put("VN","Vietnam");
		converter.put("YE","Yemen");
		converter.put("ZW","Zimbabwe");
	}

	public String getFullCountryName(String countryCode) {
		if (converter.containsKey(countryCode)) {
			return (converter.get(countryCode));
		} else {
			return (countryCode);
		}
	}

}